const fs = require('fs/promises');
const path = require('path');
const os = require('os');
const childProcess = require('child_process');

function runCommand(command, args) {
  return new Promise((resolve) => {
    const child = childProcess.spawn(command, args, {
      shell: true,
      stdio: ['ignore', 'pipe', 'pipe']
    });

    let stdout = '';
    let stderr = '';

    child.stdout.on('data', (data) => {
      stdout += data.toString();
    });

    child.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    child.on('error', () => {
      resolve(null);
    });

    child.on('close', (code) => {
      if (code !== 0) {
        resolve(null);
        return;
      }

      resolve((stdout || stderr).trim());
    });
  });
}

async function detectEnvironment() {
  const platformMap = {
    win32: 'windows',
    linux: 'linux',
    darwin: 'macos'
  };

  const npmVersion = await runCommand('npm', ['--version']);
  const gitVersion = await runCommand('git', ['--version']);
  const pythonVersion = await runCommand('python', ['--version']);

  const warnings = [];

  if (!gitVersion) {
    warnings.push('Git was not found. KORVIN can still generate local setup files now.');
  }

  if (!pythonVersion) {
    warnings.push('Python was not found. You may need Python later for dashboard or voice features.');
  }

  return {
    platform: platformMap[process.platform] || 'unknown',
    nodeVersion: process.version,
    npmVersion,
    gitVersion,
    pythonVersion,
    warnings,
    errors: []
  };
}

function buildSetupState(projectFolder, detection) {
  const absoluteProjectFolder = path.resolve(projectFolder);
  const createdAt = new Date().toISOString();

  return {
    schemaVersion: '0.1',
    featureState: 'planning-implementation',
    profile: 'quick-local',
    createdAt,
    project: {
      folder: projectFolder,
      absoluteFolder: absoluteProjectFolder
    },
    provider: {
      selected: false,
      providerType: null,
      keyHandling: 'manual-later',
      keyEnvVar: 'KORVIN_PROVIDER_KEY'
    },
    dashboard: {
      enabled: true,
      mode: 'local-only',
      host: '127.0.0.1',
      port: 3002
    },
    memory: {
      enabled: true,
      engine: 'sqlite',
      path: 'memory/korvin-memory.db'
    },
    interfaces: {
      dashboard: true,
      telegram: false,
      voicePrepared: false
    },
    security: {
      internetExposure: false,
      publicPortsConfigured: false,
      secretsWritten: false
    },
    environment: detection,
    warnings: detection.warnings
  };
}

function getTemplates(state) {
  return {
    '.env.example': `# KORVIN environment variables
# Copy this file to .env when you are ready to add local secrets.
# Do not commit .env to Git.

# Model provider key, optional until you configure a provider
KORVIN_PROVIDER_KEY=

# Dashboard local auth key, optional until local dashboard auth is enabled
KORVIN_DASHBOARD_KEY=

# LiteLLM key, optional until LiteLLM is configured
LITELLM_MASTER_KEY=
`,
    '.gitignore': `.env
*.env
memory/*.db
memory/*.sqlite
logs/*
!logs/.gitkeep
backups/*
!backups/.gitkeep
voice/input/*
!voice/input/.gitkeep
voice/output/*
!voice/output/.gitkeep
`,
    'korvin.config.json': `${JSON.stringify({
      schemaVersion: state.schemaVersion,
      profile: state.profile,
      createdAt: state.createdAt,
      dashboard: state.dashboard,
      memory: state.memory,
      provider: {
        configured: false,
        type: null,
        apiKeyEnv: 'KORVIN_PROVIDER_KEY'
      },
      interfaces: state.interfaces,
      security: state.security
    }, null, 2)}
`,
    'config/providers.example.json': `${JSON.stringify({
      provider: 'openai-compatible',
      model: 'your-model-name',
      baseUrl: 'https://api.example-provider.com/v1',
      apiKeyEnv: 'KORVIN_PROVIDER_KEY',
      notes: 'Replace these placeholders when you choose a provider. Do not place secrets in this example file.'
    }, null, 2)}
`,
    'config/litellm.example.yaml': `# Example LiteLLM configuration for local KORVIN setup.
# Replace placeholders before use.
# Do not commit real provider keys.

model_list:
  - model_name: korvin-default
    litellm_params:
      model: openai/your-model-name
      api_key: os.environ/KORVIN_PROVIDER_KEY

litellm_settings:
  drop_params: true
`,
    'config/dashboard.example.json': `${JSON.stringify({
      enabled: true,
      host: '127.0.0.1',
      port: 3002,
      auth: {
        enabled: false,
        apiKeyEnv: 'KORVIN_DASHBOARD_KEY'
      },
      notes: 'The dashboard is local-only by default. Do not bind it to 0.0.0.0 unless you understand the risk and protect access.'
    }, null, 2)}
`,
    'README.local.md': `# KORVIN Local Setup

This folder was generated by korvin init v1.

This is a local-only setup.
No services were installed.
No internet exposure was configured.
No secrets were written.

## What was created

- Placeholder environment file
- Local-only dashboard configuration
- Model provider example configuration
- LiteLLM example configuration
- Memory, data, logs, and backup folders
- Safety notes and next steps

## What was not configured

- VPS setup
- Cloudflare setup
- Telegram setup
- systemd services
- Open WebUI
- Provider keys
- Public ports

## Next step

Copy .env.example to .env only when you are ready to add local secrets.
`,
    'docs/NEXT_STEPS.md': `# KORVIN Next Steps

1. Review korvin.config.json.
2. Copy .env.example to .env when you are ready to add local secrets.
3. Add provider keys locally only.
4. Keep the dashboard local unless protected remote access is configured later.
5. Read docs/SECURITY_NOTES.md.

KORVIN init v1 created local setup files only.
`,
    'docs/SECURITY_NOTES.md': `# KORVIN Security Notes

- Do not commit .env.
- Do not paste secrets into chats or screenshots.
- The dashboard is local-only by default.
- No public ports were configured by v1.
- Cloudflare Tunnel plus Access is a future protected remote path, not automatic v1 behavior.
- Open WebUI is optional and separate from KORVIN core.
`
  };
}

async function pathExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function writeFileIfMissing(baseFolder, relativeFile, content, result) {
  const target = path.join(baseFolder, relativeFile);

  if (await pathExists(target)) {
    result.skippedFiles.push(relativeFile);
    return;
  }

  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, content, 'utf8');
  result.createdFiles.push(relativeFile);
}

async function generateProject(state) {
  const result = {
    createdDirectories: [],
    createdFiles: [],
    skippedFiles: [],
    warnings: []
  };

  const baseFolder = state.project.absoluteFolder;

  const directories = [
    '.',
    'data',
    'memory',
    'logs',
    'config',
    'docs',
    'backups'
  ];

  for (const directory of directories) {
    const target = path.join(baseFolder, directory);
    await fs.mkdir(target, { recursive: true });
    result.createdDirectories.push(directory);
  }

  const gitkeepFiles = [
    'data/.gitkeep',
    'memory/.gitkeep',
    'logs/.gitkeep',
    'backups/.gitkeep'
  ];

  for (const file of gitkeepFiles) {
    await writeFileIfMissing(baseFolder, file, '', result);
  }

  const templates = getTemplates(state);

  for (const [relativeFile, content] of Object.entries(templates)) {
    await writeFileIfMissing(baseFolder, relativeFile, content, result);
  }

  return result;
}

async function validateProject(state) {
  const baseFolder = state.project.absoluteFolder;
  const requiredFiles = [
    '.env.example',
    '.gitignore',
    'korvin.config.json',
    'README.local.md',
    'config/providers.example.json',
    'config/litellm.example.yaml',
    'config/dashboard.example.json',
    'docs/NEXT_STEPS.md',
    'docs/SECURITY_NOTES.md'
  ];

  const requiredDirectories = [
    'data',
    'memory',
    'logs',
    'config',
    'docs',
    'backups'
  ];

  const missingFiles = [];
  const missingDirectories = [];
  const invalidFiles = [];
  const warnings = [];

  for (const directory of requiredDirectories) {
    if (!(await pathExists(path.join(baseFolder, directory)))) {
      missingDirectories.push(directory);
    }
  }

  for (const file of requiredFiles) {
    if (!(await pathExists(path.join(baseFolder, file)))) {
      missingFiles.push(file);
    }
  }

  try {
    const configRaw = await fs.readFile(path.join(baseFolder, 'korvin.config.json'), 'utf8');
    const config = JSON.parse(configRaw);

    if (config.dashboard.host !== '127.0.0.1') {
      invalidFiles.push('korvin.config.json dashboard.host must be 127.0.0.1');
    }

    if (config.security.internetExposure !== false) {
      invalidFiles.push('korvin.config.json security.internetExposure must be false');
    }

    if (config.security.publicPortsConfigured !== false) {
      invalidFiles.push('korvin.config.json security.publicPortsConfigured must be false');
    }

    if (config.security.secretsWritten !== false) {
      invalidFiles.push('korvin.config.json security.secretsWritten must be false');
    }
  } catch {
    invalidFiles.push('korvin.config.json is not valid JSON');
  }

  const gitignoreRaw = await fs.readFile(path.join(baseFolder, '.gitignore'), 'utf8');

  if (!gitignoreRaw.includes('.env')) {
    invalidFiles.push('.gitignore must include .env');
  }

  return {
    valid: missingFiles.length === 0 && missingDirectories.length === 0 && invalidFiles.length === 0,
    missingFiles,
    missingDirectories,
    invalidFiles,
    warnings
  };
}

function printEnvironment(detection) {
  console.log('Environment detection:');
  console.log(`- Platform: ${detection.platform}`);
  console.log(`- Node.js: ${detection.nodeVersion}`);
  console.log(`- npm: ${detection.npmVersion || 'not found'}`);
  console.log(`- Git: ${detection.gitVersion || 'not found'}`);
  console.log(`- Python: ${detection.pythonVersion || 'not found'}`);

  if (detection.warnings.length > 0) {
    console.log('');
    console.log('Warnings:');
    for (const warning of detection.warnings) {
      console.log(`- ${warning}`);
    }
  }
}

function printSuccess(state, generation, validation) {
  console.log('');
  console.log('KORVIN local setup files created.');
  console.log('');
  console.log(`Project folder: ${state.project.folder}`);
  console.log('');
  console.log(`Created files: ${generation.createdFiles.length}`);
  console.log(`Skipped existing files: ${generation.skippedFiles.length}`);
  console.log('');
  console.log('Safety summary:');
  console.log('- No services were installed.');
  console.log('- No internet exposure was configured.');
  console.log('- No provider keys were requested.');
  console.log('- No secrets were written.');
  console.log('- Dashboard default is 127.0.0.1.');
  console.log('');

  if (!validation.valid) {
    console.log('Validation failed.');
    console.log(validation);
    process.exitCode = 3;
    return;
  }

  console.log('Validation passed.');
  console.log('');
  console.log('Next step:');
  console.log(`cd ${state.project.folder}`);
  console.log('Review README.local.md and docs/SECURITY_NOTES.md');
}

async function runInit(args = []) {
  const projectFolder = args[0] || './korvin-local';

  console.log(`KORVIN init v1

This command creates a safe local-only KORVIN project configuration.

Current v1 boundaries:
- Quick Local Setup only
- No VPS setup
- No Cloudflare setup
- No Telegram setup
- No systemd setup
- No public ports
- No provider keys requested
- No secrets written
`);

  const detection = await detectEnvironment();
  printEnvironment(detection);

  const state = buildSetupState(projectFolder, detection);

  console.log('');
  console.log('Setup review:');
  console.log(`- Profile: ${state.profile}`);
  console.log(`- Project folder: ${state.project.folder}`);
  console.log(`- Dashboard host: ${state.dashboard.host}`);
  console.log('- Internet exposure: false');
  console.log('- Secrets written: false');

  const generation = await generateProject(state);
  const validation = await validateProject(state);

  printSuccess(state, generation, validation);
}

module.exports = {
  runInit
};